"""Prompt chain: fixed sequential stages with programmatic gates.

Generated by VG Select: 3A (Automated Agentic Architecture) v0.4.0. Search for TODO."""

from langgraph.graph import END, START, StateGraph

from .agents import chat_model
from .state import State


def extract(state: State) -> dict:
    """Pull candidate fields from the input (tools if needed)."""
    prev = state.get("draft") or state.get("outline") or ""
    llm = chat_model("extract")
    msg = llm.invoke([("system", "TODO: instructions for: Pull candidate fields from the input (tools if needed)."), ("user", f"Request: {state['request']}\n\nPrevious stage output:\n{prev}")])
    text = msg.content if isinstance(msg.content, str) else str(msg.content)
    return {"draft": text, "answer": text, "messages": [msg]}


def validate(state: State) -> dict:
    """Schema and business-rule checks in code; reject or route back. (code gate: validate the previous stage's output)."""
    # TODO: implement checks; set checked=False to route back
    return {"checked": True}


def finalize(state: State) -> dict:
    """Resolve ambiguities and emit the final structured record."""
    prev = state.get("draft") or state.get("outline") or ""
    llm = chat_model("finalize")
    msg = llm.invoke([("system", "TODO: instructions for: Resolve ambiguities and emit the final structured record."), ("user", f"Request: {state['request']}\n\nPrevious stage output:\n{prev}")])
    text = msg.content if isinstance(msg.content, str) else str(msg.content)
    return {"draft": text, "answer": text, "messages": [msg]}


def build_graph():
    g = StateGraph(State)
    g.add_node("extract", extract)
    g.add_node("validate", validate)
    g.add_node("finalize", finalize)
    g.add_edge(START, "extract")
    g.add_edge("extract", "validate")
    g.add_edge("validate", "finalize")
    g.add_edge("finalize", END)
    return g.compile()
