"""LangGraph (LangChain) project skeleton, one template per topology.

The generated project is a starting point: state, graph wiring, per-role
agents on the recommended model tiers, tool stubs, termination limits and a
smoke test. Every place that needs product-specific work is marked TODO.
"""

from __future__ import annotations

import json
import re
import textwrap
from typing import TYPE_CHECKING

from .. import PRODUCT_NAME, __version__
from ..estimator import worker_count

if TYPE_CHECKING:
    from ..recommender import Recommendation


def slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return s or "app"


def ident(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    if not s or s[0].isdigit():
        s = "n_" + s
    return s


def _tools(rec: "Recommendation") -> list[str]:
    p = rec.profile
    given = p.extra.get("tools") if isinstance(p.extra.get("tools"), list) else []
    names = [ident(str(t)) for t in given if str(t) and not str(t).startswith("~")]
    if not names and p.uses_tools:
        names = [f"tool_{i + 1}" for i in range(min(p.tool_count, 5))]
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n); out.append(n)
    return out[:20]


def generate(rec: "Recommendation") -> dict[str, str]:
    p = rec.profile
    topo = rec.primary.topology.id
    tools = _tools(rec)
    comps = rec.plan.components
    files: dict[str, str] = {}
    files["README.md"] = _readme(rec, topo, tools)
    files["ARCHITECTURE.md"] = rec.to_markdown()
    files["vgselect_profile.json"] = p.to_json()
    files["requirements.txt"] = "langgraph>=0.2\nlangchain>=0.3\nlangchain-core>=0.3\nlangchain-anthropic>=0.3\npython-dotenv>=1.0\npytest>=8\n"
    files[".env.example"] = "ANTHROPIC_API_KEY=sk-ant-...\n"
    files[".gitignore"] = ".env\n__pycache__/\n*.pyc\n.venv/\n"
    files["app/__init__.py"] = ""
    files["app/config.py"] = _config(rec, comps)
    files["app/tools.py"] = _tools_py(tools, p)
    files["app/agents.py"] = _agents_py()
    files["app/state.py"] = _state_py(topo)
    files["app/graph.py"] = _GRAPH[topo](rec, tools)
    files["main.py"] = _main_py(topo)
    files["tests/test_graph.py"] = _test_py()
    return files


# ---------------------------------------------------------------- shared files

def _readme(rec, topo, tools) -> str:
    p = rec.profile
    best = rec.primary
    return textwrap.dedent(f"""\
    # {p.name} - LangGraph skeleton

    Generated by {PRODUCT_NAME} v{__version__} for the recommended topology
    **{best.topology.name}** (`{topo}`). See `ARCHITECTURE.md` for the full
    recommendation, the ranked alternatives, the plan and the evidence.

    ## What is in here

    | File | Purpose |
    |---|---|
    | `app/graph.py` | The LangGraph `StateGraph` wiring the recommended topology |
    | `app/agents.py` | Factory for role agents (model per tier, system prompt, tools) |
    | `app/config.py` | Model IDs per role, effort, termination limits, budgets |
    | `app/tools.py` | Tool stubs{(' for: ' + ', '.join(tools)) if tools else ''} - fill in the bodies |
    | `app/state.py` | Graph state (`TypedDict`) |
    | `main.py` | Runs one request end to end |
    | `tests/test_graph.py` | Smoke test: graph compiles, state shape is right |
    | `vgselect_profile.json` | The workload profile this skeleton was generated from |

    ## Run

    ```bash
    python -m venv .venv && source .venv/bin/activate
    pip install -r requirements.txt
    cp .env.example .env   # add your ANTHROPIC_API_KEY
    python main.py "your first request"
    pytest
    ```

    ## Fill in (search for TODO)

    1. `app/tools.py`: implement each tool; keep descriptions precise - agents choose tools by description.
    2. `app/config.py`: confirm model IDs and termination limits; set `MAX_TOOL_CALLS` and `RECURSION_LIMIT` from your latency budget ({p.latency_budget_s:.0f}s).
    3. `app/graph.py`: adjust prompts and the decomposition{' (worker briefs must carry objective, output format, sources, boundaries)' if topo in ('orchestrator_workers', 'hierarchical') else ''}.
    4. Build the ~20-query eval before adding structure; the recommendation assumes you will measure.

    ## Guardrails already wired

    - Recursion/turn limits on every loop (`RECURSION_LIMIT`, `MAX_ITERATIONS`).
    - Model per role: Opus-tier for orchestration/synthesis, Sonnet/Haiku-tier for workers and routers.
    - A verification step before the final answer where the plan calls for it.
    {'- Approval gate hook for irreversible tools (`app/tools.py: requires_approval`).' if p.tool_side_effects == 'irreversible' else ''}
    """)


def _config(rec, comps) -> str:
    p = rec.profile
    roles = "\n".join(f'    "{ident(c.id)}": Role(name={c.name!r}, model={c.model_id!r}, effort={c.effort!r}, tier={c.tier!r}),' for c in comps)
    return textwrap.dedent(f'''\
    """Models, effort and limits per role. Generated from the VG Select: 3A plan."""

    from dataclasses import dataclass


    @dataclass(frozen=True)
    class Role:
        name: str
        model: str
        effort: str
        tier: str


    # Model IDs are current-generation defaults; substitute your approved equivalents.
    ROLES: dict[str, Role] = {{
    {roles}
    }}

    # Termination limits (MAST: "unaware of termination" and step repetition are ~28% of multi-agent failures).
    RECURSION_LIMIT = {max(25, min(200, int(p.tool_calls_per_task) * 3 + 20))}   # LangGraph steps per request
    MAX_TOOL_CALLS = {max(3, int(p.tool_calls_per_task) or 3)}          # per agent per request
    MAX_ITERATIONS = {3 if p.accuracy_priority >= 5 else 2}             # evaluator / refinement loops
    MAX_WORKERS = {worker_count(p) if rec.primary.topology.id in ('orchestrator_workers', 'hierarchical') else max(2, min(p.parallel_subtasks, 20))}
    LATENCY_BUDGET_S = {p.latency_budget_s}

    # Thinking / effort: langchain-anthropic passes provider params through model_kwargs.
    # Adaptive thinking is the default on current Claude models; tune effort per role, e.g.
    #   ChatAnthropic(model=..., model_kwargs={{"output_config": {{"effort": "high"}}}})
    DEFAULT_MAX_TOKENS = 4096
    ''')


def _tools_py(tools, p) -> str:
    stubs = "\n\n".join(textwrap.dedent(f'''\
        @tool
        def {t}(query: str) -> str:
            """TODO: describe precisely what `{t}` does, its inputs and what it returns.
            Agents choose tools by this description."""
            # TODO: implement
            return f"{t} result for: {{query}}"''') for t in tools) or textwrap.dedent('''\
        # No tools were declared in the profile. Add @tool functions here and list them in TOOLS.''')
    gate = ""
    if p.tool_side_effects == "irreversible":
        gate = textwrap.dedent('''\

        IRREVERSIBLE = {  # TODO: list tool names whose effects cannot be undone
        }


        def requires_approval(tool_name: str) -> bool:
            """Wire this into an interrupt (langgraph.types.interrupt) or a human approval step
            before executing irreversible tools."""
            return tool_name in IRREVERSIBLE
        ''')
    return textwrap.dedent('''\
        """Tool definitions. Keep tools few, distinct and well described."""

        from langchain_core.tools import tool


        ''') + stubs + "\n\n\nTOOLS = [" + ", ".join(tools) + "]\n" + gate


def _agents_py() -> str:
    return textwrap.dedent('''\
        """Role agent factory. Uses langchain's create_agent (LangChain 1.x) with a fallback to
        langgraph.prebuilt.create_react_agent (LangGraph 0.2/0.3)."""

        from langchain_anthropic import ChatAnthropic

        from .config import DEFAULT_MAX_TOKENS, ROLES

        try:  # LangChain 1.x
            from langchain.agents import create_agent as _create_agent

            def _build(model, tools, system_prompt):
                return _create_agent(model, tools=tools, system_prompt=system_prompt)
        except ImportError:  # LangGraph 0.2 / 0.3
            from langgraph.prebuilt import create_react_agent as _create_react_agent

            def _build(model, tools, system_prompt):
                return _create_react_agent(model, tools, prompt=system_prompt)


        def chat_model(role_id: str, **kwargs) -> ChatAnthropic:
            role = ROLES[role_id]
            return ChatAnthropic(model=role.model, max_tokens=kwargs.pop("max_tokens", DEFAULT_MAX_TOKENS), **kwargs)


        def role_agent(role_id: str, system_prompt: str, tools=None):
            """A tool-using agent for one role of the plan."""
            return _build(chat_model(role_id), list(tools or []), system_prompt)


        def last_text(result) -> str:
            """Final assistant text from an agent/graph result."""
            msgs = result["messages"] if isinstance(result, dict) else result
            for m in reversed(msgs):
                content = getattr(m, "content", None)
                if getattr(m, "type", "") == "ai" and content:
                    if isinstance(content, list):
                        return "".join(b.get("text", "") for b in content if isinstance(b, dict))
                    return str(content)
            return ""
        ''')


def _state_py(topo) -> str:
    extra = {
        "router": "    route: str\n",
        "parallel_sectioning": "    sections: list[str]\n    results: Annotated[list[str], operator.add]\n",
        "parallel_voting": "    votes: Annotated[list[str], operator.add]\n",
        "evaluator_optimizer": "    draft: str\n    feedback: str\n    accepted: bool\n    iteration: int\n",
        "orchestrator_workers": "    plan: list[dict]\n    reports: Annotated[list[str], operator.add]\n    draft: str\n",
        "hierarchical": "    domains: list[str]\n    domain_reports: Annotated[list[str], operator.add]\n",
        "handoff_network": "    active: str\n    handoffs: int\n",
        "prompt_chain": "    outline: str\n    draft: str\n    checked: bool\n",
    }.get(topo, "")
    return textwrap.dedent('''\
        """Graph state."""

        import operator
        from typing import Annotated, TypedDict

        from langchain_core.messages import AnyMessage
        from langgraph.graph.message import add_messages


        class State(TypedDict, total=False):
            request: str
            messages: Annotated[list[AnyMessage], add_messages]
            answer: str
        ''') + extra


def _main_py(topo) -> str:
    return textwrap.dedent('''\
        """Run one request through the graph."""

        import sys

        from dotenv import load_dotenv

        from app.config import RECURSION_LIMIT
        from app.graph import build_graph

        load_dotenv()

        if __name__ == "__main__":
            request = " ".join(sys.argv[1:]) or "TODO: put a representative request here"
            graph = build_graph()
            result = graph.invoke({"request": request, "messages": []}, config={"recursion_limit": RECURSION_LIMIT})
            print(result.get("answer") or result)
        ''')


def _test_py() -> str:
    return textwrap.dedent('''\
        """Smoke tests that need no API key: the graph compiles and exposes the expected nodes."""

        from app.graph import build_graph


        def test_graph_compiles():
            g = build_graph()
            nodes = set(g.get_graph().nodes)
            assert "__start__" in nodes and "__end__" in nodes
            assert len(nodes) >= 3
        ''')


# ---------------------------------------------------------------- graph templates

def _hdr(doc: str) -> str:
    return f'"""{doc}\n\nGenerated by {PRODUCT_NAME} v{__version__}. Search for TODO."""\n\n'


def _g_single_call(rec, tools) -> str:
    return _hdr("Single model call: retrieval in code, then one answer.") + textwrap.dedent('''\
        from langgraph.graph import END, START, StateGraph

        from .agents import chat_model
        from .state import State

        SYSTEM = "TODO: system prompt. State the task, the audience and the output format."


        def retrieve(state: State) -> dict:
            """TODO: deterministic retrieval in code (classic RAG). Return context for the prompt."""
            return {"messages": [("system", SYSTEM)]}


        def answer(state: State) -> dict:
            llm = chat_model("llm")
            msg = llm.invoke([("system", SYSTEM), ("user", state["request"])])
            return {"answer": msg.content if isinstance(msg.content, str) else str(msg.content), "messages": [msg]}


        def build_graph():
            g = StateGraph(State)
            g.add_node("retrieve", retrieve)
            g.add_node("answer", answer)
            g.add_edge(START, "retrieve")
            g.add_edge("retrieve", "answer")
            g.add_edge("answer", END)
            return g.compile()
        ''')


def _g_single_agent(rec, tools) -> str:
    return _hdr("Single agent with tools: one tool-use loop owns the whole task.") + textwrap.dedent('''\
        from langgraph.graph import END, START, StateGraph

        from .agents import last_text, role_agent
        from .state import State
        from .tools import TOOLS

        SYSTEM = (
            "TODO: role, goal and boundaries. Say which tools to prefer and when to stop. "
            "Ask for clarification only when the request is ambiguous."
        )


        def agent(state: State) -> dict:
            runner = role_agent("agent", SYSTEM, TOOLS)
            result = runner.invoke({"messages": [("user", state["request"])]})
            return {"answer": last_text(result), "messages": result["messages"]}


        def build_graph():
            g = StateGraph(State)
            g.add_node("agent", agent)
            g.add_edge(START, "agent")
            g.add_edge("agent", END)
            return g.compile()
        ''')


def _g_prompt_chain(rec, tools) -> str:
    stages = [c for c in rec.plan.components]
    node_defs = []
    for c in stages:
        cid = ident(c.id)
        if c.tier == "code":
            node_defs.append(textwrap.dedent(f'''\
                def {cid}(state: State) -> dict:
                    """{c.role} (code gate: validate the previous stage's output)."""
                    # TODO: implement checks; set checked=False to route back
                    return {{"checked": True}}
                '''))
        else:
            node_defs.append(textwrap.dedent(f'''\
                def {cid}(state: State) -> dict:
                    """{c.role}"""
                    prev = state.get("draft") or state.get("outline") or ""
                    llm = chat_model("{cid}")
                    msg = llm.invoke([("system", "TODO: instructions for: {c.role}"), ("user", f"Request: {{state['request']}}\\n\\nPrevious stage output:\\n{{prev}}")])
                    text = msg.content if isinstance(msg.content, str) else str(msg.content)
                    return {{"draft": text, "answer": text, "messages": [msg]}}
                '''))
    ids = [ident(c.id) for c in stages]
    edges = "\n".join(f'    g.add_edge("{a}", "{b}")' for a, b in zip(ids, ids[1:]))
    return _hdr("Prompt chain: fixed sequential stages with programmatic gates.") + textwrap.dedent('''\
        from langgraph.graph import END, START, StateGraph

        from .agents import chat_model
        from .state import State


        ''') + "\n\n".join(node_defs) + textwrap.dedent(f'''\


        def build_graph():
            g = StateGraph(State)
        ''') + "\n".join(f'    g.add_node("{i}", {i})' for i in ids) + f'\n    g.add_edge(START, "{ids[0]}")\n' + edges + f'\n    g.add_edge("{ids[-1]}", END)\n    return g.compile()\n'


def _g_router(rec, tools) -> str:
    handlers = [c for c in rec.plan.components if c.id != "router"]
    hids = [ident(c.id) for c in handlers]
    labels = [c.name for c in handlers]
    node_defs = "\n\n".join(textwrap.dedent(f'''\
        def {hid}(state: State) -> dict:
            """{c.role}"""
            runner = role_agent("{hid}", "TODO: system prompt for {c.name}: only this domain's instructions and tools.", TOOLS)
            result = runner.invoke({{"messages": [("user", state["request"])]}})
            return {{"answer": last_text(result), "messages": result["messages"]}}
        ''') for hid, c in zip(hids, handlers))
    return _hdr("Router: a small-model classifier dispatches to one specialist.") + textwrap.dedent(f'''\
        from typing import Literal

        from pydantic import BaseModel
        from langgraph.graph import END, START, StateGraph

        from .agents import chat_model, last_text, role_agent
        from .state import State
        from .tools import TOOLS

        ROUTES = {json.dumps(dict(zip(hids, labels)))}


        class Route(BaseModel):
            route: Literal[{", ".join(repr(h) for h in hids)}]


        def router(state: State) -> dict:
            llm = chat_model("router", max_tokens=64).with_structured_output(Route)
            choices = "\\n".join(f"- {{k}}: {{v}}" for k, v in ROUTES.items())
            decision = llm.invoke([("system", "Classify the request into exactly one route:\\n" + choices), ("user", state["request"])])
            return {{"route": decision.route}}


        ''') + node_defs + textwrap.dedent(f'''\


        def build_graph():
            g = StateGraph(State)
            g.add_node("router", router)
        ''') + "\n".join(f'    g.add_node("{h}", {h})' for h in hids) + (
        '\n    g.add_edge(START, "router")\n'
        '    g.add_conditional_edges("router", lambda s: s["route"], {h: h for h in ROUTES})\n'
    ) + "\n".join(f'    g.add_edge("{h}", END)' for h in hids) + "\n    return g.compile()\n"


def _g_parallel_sectioning(rec, tools) -> str:
    sections = [c.name.replace(" worker", "") for c in rec.plan.components if c.parallel_group == "fanout"]
    return _hdr("Parallel sectioning: code-defined fan-out over independent sections, then aggregate.") + textwrap.dedent(f'''\
        from langgraph.graph import END, START, StateGraph
        from langgraph.types import Send

        from .agents import chat_model, last_text, role_agent
        from .config import MAX_WORKERS
        from .state import State
        from .tools import TOOLS

        SECTIONS = {json.dumps(sections)}  # TODO: the independent sections of one request


        def split(state: State) -> dict:
            """Deterministic split. Replace with your own partitioning if sections depend on the input."""
            return {{"sections": SECTIONS[:MAX_WORKERS], "results": []}}


        def fan_out(state: State):
            return [Send("section", {{"request": state["request"], "section": s}}) for s in state["sections"]]


        def section(payload: dict) -> dict:
            runner = role_agent("section_1", f"Handle only the '{{payload['section']}}' section. Return findings only, with evidence.", TOOLS)
            result = runner.invoke({{"messages": [("user", payload["request"])]}})
            return {{"results": [f"## {{payload['section']}}\\n{{last_text(result)}}"]}}


        def merge(state: State) -> dict:
            """Merge in code when possible; use one synthesis call when prose is needed."""
            llm = chat_model("merge")
            msg = llm.invoke([("system", "Merge these section results into one consistent answer. Do not add facts."), ("user", "\\n\\n".join(state["results"]))])
            text = msg.content if isinstance(msg.content, str) else str(msg.content)
            return {{"answer": text, "messages": [msg]}}


        def build_graph():
            g = StateGraph(State)
            g.add_node("split", split)
            g.add_node("section", section)
            g.add_node("merge", merge)
            g.add_edge(START, "split")
            g.add_conditional_edges("split", fan_out, ["section"])
            g.add_edge("section", "merge")
            g.add_edge("merge", END)
            return g.compile()
        ''')


def _g_parallel_voting(rec, tools) -> str:
    votes = len([c for c in rec.plan.components if c.parallel_group == "votes"])
    discrete = rec.profile.output_type in ("short_answer", "structured_data")
    return _hdr("Parallel voting: independent attempts, then majority (code) or a judge call.") + textwrap.dedent(f'''\
        from collections import Counter

        from langgraph.graph import END, START, StateGraph
        from langgraph.types import Send

        from .agents import chat_model, last_text, role_agent
        from .state import State
        from .tools import TOOLS

        N_VOTES = {votes}
        DISCRETE = {discrete}  # majority vote in code when the answer is discrete; otherwise a judge call


        def fan_out(state: State):
            # Vary the prompt/temperature per voter for diversity.
            return [Send("vote", {{"request": state["request"], "i": i}}) for i in range(N_VOTES)]


        def vote(payload: dict) -> dict:
            runner = role_agent("vote_1", f"Independent attempt #{{payload['i'] + 1}}. TODO: task instructions. Answer with the final result only.", TOOLS)
            result = runner.invoke({{"messages": [("user", payload["request"])]}})
            return {{"votes": [last_text(result).strip()]}}


        def decide(state: State) -> dict:
            if DISCRETE:
                winner, _ = Counter(state["votes"]).most_common(1)[0]
                return {{"answer": winner}}
            llm = chat_model("judge")
            msg = llm.invoke([("system", "You are the judge. Merge the candidate answers into the best single answer; flag disagreements."),
                              ("user", "\\n\\n---\\n\\n".join(state["votes"]))])
            return {{"answer": msg.content if isinstance(msg.content, str) else str(msg.content), "messages": [msg]}}


        def build_graph():
            g = StateGraph(State)
            g.add_node("start", lambda s: {{"votes": []}})
            g.add_node("vote", vote)
            g.add_node("decide", decide)
            g.add_edge(START, "start")
            g.add_conditional_edges("start", fan_out, ["vote"])
            g.add_edge("vote", "decide")
            g.add_edge("decide", END)
            return g.compile()
        ''')


def _g_evaluator_optimizer(rec, tools) -> str:
    return _hdr("Evaluator-optimizer: generate, evaluate against explicit criteria, refine until accepted or the budget is hit.") + textwrap.dedent('''\
        from pydantic import BaseModel
        from langgraph.graph import END, START, StateGraph

        from .agents import chat_model, last_text, role_agent
        from .config import MAX_ITERATIONS
        from .state import State
        from .tools import TOOLS

        CRITERIA = "TODO: explicit, checkable acceptance criteria (tests to pass, rubric, schema)."


        class Verdict(BaseModel):
            accepted: bool
            feedback: str


        def generate(state: State) -> dict:
            feedback = state.get("feedback", "")
            prompt = state["request"] + (f"\\n\\nRevise the previous draft using this feedback:\\n{feedback}\\n\\nPrevious draft:\\n{state.get('draft', '')}" if feedback else "")
            runner = role_agent("generator", "TODO: generator instructions.", TOOLS)
            result = runner.invoke({"messages": [("user", prompt)]})
            return {"draft": last_text(result), "iteration": state.get("iteration", 0) + 1, "messages": result["messages"]}


        def evaluate(state: State) -> dict:
            # TODO: run tests/validators here first; only ask the model for what code cannot check.
            llm = chat_model("evaluator").with_structured_output(Verdict)
            v = llm.invoke([("system", f"Evaluate the draft against these criteria and give actionable feedback:\\n{CRITERIA}"),
                            ("user", f"Request:\\n{state['request']}\\n\\nDraft:\\n{state['draft']}")])
            return {"accepted": v.accepted, "feedback": v.feedback}


        def route(state: State) -> str:
            if state.get("accepted") or state.get("iteration", 0) >= MAX_ITERATIONS:
                return "finish"
            return "generate"


        def finish(state: State) -> dict:
            return {"answer": state["draft"]}


        def build_graph():
            g = StateGraph(State)
            g.add_node("generate", generate)
            g.add_node("evaluate", evaluate)
            g.add_node("finish", finish)
            g.add_edge(START, "generate")
            g.add_edge("generate", "evaluate")
            g.add_conditional_edges("evaluate", route, {"generate": "generate", "finish": "finish"})
            g.add_edge("finish", END)
            return g.compile()
        ''')


def _g_orchestrator_workers(rec, tools) -> str:
    workers = [c for c in rec.plan.components if c.parallel_group == "workers"]
    has_critic = any(c.id == "critic" for c in rec.plan.components)
    names = [c.name for c in workers]
    return _hdr("Orchestrator + workers: the lead plans and briefs, workers run in parallel in fresh contexts, the lead verifies and synthesises.") + textwrap.dedent(f'''\
        from pydantic import BaseModel
        from langgraph.graph import END, START, StateGraph
        from langgraph.types import Send

        from .agents import chat_model, last_text, role_agent
        from .config import MAX_WORKERS
        from .state import State
        from .tools import TOOLS

        # Suggested worker roster from the plan (the lead may spawn fewer):
        WORKER_ROSTER = {json.dumps(names)}

        LEAD_SYSTEM = (
            "You are the lead. Break the request into at most {{n}} independent, self-contained sub-tasks. "
            "Each brief MUST include: objective, expected output format, tools/sources to use, boundaries (what not to do), "
            "and expected effort (simple fact-finding ~3-10 tool calls; comparisons ~10-15). Workers see none of this conversation."
        )


        class Brief(BaseModel):
            name: str
            objective: str
            output_format: str
            sources: str
            boundaries: str


        class Plan(BaseModel):
            briefs: list[Brief]


        def plan(state: State) -> dict:
            llm = chat_model("lead").with_structured_output(Plan)
            p = llm.invoke([("system", LEAD_SYSTEM.format(n=MAX_WORKERS)), ("user", state["request"])])
            return {{"plan": [b.model_dump() for b in p.briefs[:MAX_WORKERS]], "reports": []}}


        def fan_out(state: State):
            return [Send("worker", {{"request": state["request"], "brief": b}}) for b in state["plan"]]


        def worker(payload: dict) -> dict:
            b = payload["brief"]
            system = (f"You own one sub-task: {{b['objective']}}\\nOutput format: {{b['output_format']}}\\n"
                      f"Sources/tools: {{b['sources']}}\\nBoundaries: {{b['boundaries']}}\\n"
                      "Return compressed findings with evidence/citations, not raw material.")
            runner = role_agent("worker_1", system, TOOLS)
            result = runner.invoke({{"messages": [("user", payload["request"])]}})
            return {{"reports": [f"### {{b['name']}}\\n{{last_text(result)}}"]}}


        def synthesise(state: State) -> dict:
            llm = chat_model("lead")
            msg = llm.invoke([("system", "Verify the worker reports against each other, resolve conflicts, and write the final answer. Keep one voice."),
                              ("user", f"Request:\\n{{state['request']}}\\n\\nReports:\\n" + "\\n\\n".join(state["reports"]))])
            text = msg.content if isinstance(msg.content, str) else str(msg.content)
            return {{"draft": text, "answer": text, "messages": [msg]}}
        ''') + (textwrap.dedent('''\


        def verify(state: State) -> dict:
            """Independent read-only check before returning (task-verification failures are ~25% of multi-agent failures)."""
            llm = chat_model("critic")
            msg = llm.invoke([("system", "Check the draft against the reports. List unsupported claims and fix them; return the corrected answer."),
                              ("user", f"Draft:\\n{state['draft']}\\n\\nReports:\\n" + "\\n\\n".join(state["reports"]))])
            return {"answer": msg.content if isinstance(msg.content, str) else str(msg.content), "messages": [msg]}
        ''') if has_critic else "") + textwrap.dedent(f'''\


        def build_graph():
            g = StateGraph(State)
            g.add_node("plan", plan)
            g.add_node("worker", worker)
            g.add_node("synthesise", synthesise)
            {'g.add_node("verify", verify)' if has_critic else ''}
            g.add_edge(START, "plan")
            g.add_conditional_edges("plan", fan_out, ["worker"])
            g.add_edge("worker", "synthesise")
            {'g.add_edge("synthesise", "verify")' if has_critic else ''}
            g.add_edge({'"verify"' if has_critic else '"synthesise"'}, END)
            return g.compile()
        ''')


def _g_hierarchical(rec, tools) -> str:
    leads = [c for c in rec.plan.components if c.parallel_group == "leads"]
    domains = [c.name.replace(" lead", "") for c in leads]
    return _hdr("Hierarchical: top orchestrator -> domain leads (each a subgraph) -> workers.") + textwrap.dedent(f'''\
        from pydantic import BaseModel
        from langgraph.graph import END, START, StateGraph
        from langgraph.types import Send

        from .agents import chat_model, last_text, role_agent
        from .config import MAX_WORKERS
        from .state import State
        from .tools import TOOLS

        DOMAINS = {json.dumps(domains)}


        class Brief(BaseModel):
            name: str
            objective: str
            output_format: str
            boundaries: str


        class Plan(BaseModel):
            briefs: list[Brief]


        # ---- domain lead subgraph (same shape as orchestrator-workers, scoped to one domain)

        class LeadState(dict):
            pass


        def lead_plan(state: dict) -> dict:
            llm = chat_model("lead_1").with_structured_output(Plan)
            p = llm.invoke([("system", f"You lead the '{{state['domain']}}' domain. Split the request into at most {{max(2, MAX_WORKERS // max(1, len(DOMAINS)))}} self-contained worker briefs."),
                            ("user", state["request"])])
            return {{"plan": [b.model_dump() for b in p.briefs], "reports": []}}


        def lead_fan_out(state: dict):
            return [Send("lead_worker", {{"request": state["request"], "domain": state["domain"], "brief": b}}) for b in state["plan"]]


        def lead_worker(payload: dict) -> dict:
            b = payload["brief"]
            runner = role_agent("lead_1_w1", f"Domain: {{payload['domain']}}. Sub-task: {{b['objective']}}. Output: {{b['output_format']}}. Boundaries: {{b['boundaries']}}. Return concise findings with evidence.", TOOLS)
            result = runner.invoke({{"messages": [("user", payload["request"])]}})
            return {{"reports": [f"#### {{b['name']}}\\n{{last_text(result)}}"]}}


        def lead_synth(state: dict) -> dict:
            llm = chat_model("lead_1")
            msg = llm.invoke([("system", f"Verify and synthesise the '{{state['domain']}}' reports into one domain report."), ("user", "\\n\\n".join(state["reports"]))])
            text = msg.content if isinstance(msg.content, str) else str(msg.content)
            return {{"domain_reports": [f"## {{state['domain']}}\\n{{text}}"]}}


        def build_lead_subgraph():
            import operator
            from typing import Annotated, TypedDict

            class LS(TypedDict, total=False):
                request: str
                domain: str
                plan: list[dict]
                reports: Annotated[list[str], operator.add]
                domain_reports: Annotated[list[str], operator.add]

            g = StateGraph(LS)
            g.add_node("lead_plan", lead_plan)
            g.add_node("lead_worker", lead_worker)
            g.add_node("lead_synth", lead_synth)
            g.add_edge(START, "lead_plan")
            g.add_conditional_edges("lead_plan", lead_fan_out, ["lead_worker"])
            g.add_edge("lead_worker", "lead_synth")
            g.add_edge("lead_synth", END)
            return g.compile()


        # ---- top level

        def top_plan(state: State) -> dict:
            return {{"domains": DOMAINS, "domain_reports": []}}


        def top_fan_out(state: State):
            return [Send("lead", {{"request": state["request"], "domain": d}}) for d in state["domains"]]


        def top_synth(state: State) -> dict:
            llm = chat_model("top")
            msg = llm.invoke([("system", "Integrate the domain reports into the final deliverable. Resolve conflicts explicitly."),
                              ("user", f"Request:\\n{{state['request']}}\\n\\n" + "\\n\\n".join(state["domain_reports"]))])
            text = msg.content if isinstance(msg.content, str) else str(msg.content)
            return {{"answer": text, "messages": [msg]}}


        def build_graph():
            g = StateGraph(State)
            g.add_node("top_plan", top_plan)
            g.add_node("lead", build_lead_subgraph())
            g.add_node("top_synth", top_synth)
            g.add_edge(START, "top_plan")
            g.add_conditional_edges("top_plan", top_fan_out, ["lead"])
            g.add_edge("lead", "top_synth")
            g.add_edge("top_synth", END)
            return g.compile()
        ''')


def _g_handoff_network(rec, tools) -> str:
    specs = [c for c in rec.plan.components]
    sids = [ident(c.id) for c in specs]
    names = [c.name for c in specs]
    node_defs = "\n\n".join(textwrap.dedent(f'''\
        def {sid}(state: State) -> dict:
            return _specialist("{sid}", "{name}", state)
        ''') for sid, name in zip(sids, names))
    return _hdr("Specialist handoffs: the active specialist answers or transfers the conversation to a peer with an explicit state summary.") + textwrap.dedent(f'''\
        from typing import Literal

        from pydantic import BaseModel
        from langgraph.graph import END, START, StateGraph

        from .agents import chat_model, last_text, role_agent
        from .state import State
        from .tools import TOOLS

        SPECIALISTS = {json.dumps(dict(zip(sids, names)))}
        MAX_HANDOFFS = 3  # prevent ping-pong between specialists


        class Decision(BaseModel):
            action: Literal["answer", "handoff"]
            handoff_to: str | None = None
            state_summary: str = ""


        def _specialist(sid: str, name: str, state: State) -> dict:
            # TODO: give each specialist its own tools subset instead of TOOLS.
            runner = role_agent(sid, f"You are the {{name}}. Handle the conversation while it is about your domain. If it is not, say so.", TOOLS)
            result = runner.invoke({{"messages": [("user", state["request"])]}})
            text = last_text(result)
            decider = chat_model(sid, max_tokens=256).with_structured_output(Decision)
            d = decider.invoke([("system", "Decide: answer, or hand off to one of: " + ", ".join(SPECIALISTS) + ". When handing off, summarise the user goal, facts gathered and actions taken."),
                                ("user", f"Request: {{state['request']}}\\n\\nDraft reply: {{text}}")])
            if d.action == "handoff" and d.handoff_to in SPECIALISTS and state.get("handoffs", 0) < MAX_HANDOFFS:
                return {{"active": d.handoff_to, "handoffs": state.get("handoffs", 0) + 1, "request": state["request"] + "\\n\\n[Handoff state]: " + d.state_summary}}
            return {{"active": "done", "answer": text, "messages": result["messages"]}}


        ''') + node_defs + textwrap.dedent(f'''\


        def entry(state: State) -> dict:
            return {{"active": state.get("active") or "{sids[0]}", "handoffs": 0}}


        def route(state: State) -> str:
            return END if state["active"] == "done" else state["active"]


        def build_graph():
            g = StateGraph(State)
            g.add_node("entry", entry)
        ''') + "\n".join(f'    g.add_node("{s}", {s})' for s in sids) + (
        '\n    g.add_edge(START, "entry")\n'
        '    g.add_conditional_edges("entry", route, {**{s: s for s in SPECIALISTS}, END: END})\n'
    ) + "\n".join(f'    g.add_conditional_edges("{s}", route, {{**{{x: x for x in SPECIALISTS}}, END: END}})' for s in sids) + "\n    return g.compile()\n"


_GRAPH = {
    "single_call": _g_single_call,
    "single_agent": _g_single_agent,
    "prompt_chain": _g_prompt_chain,
    "router": _g_router,
    "parallel_sectioning": _g_parallel_sectioning,
    "parallel_voting": _g_parallel_voting,
    "evaluator_optimizer": _g_evaluator_optimizer,
    "orchestrator_workers": _g_orchestrator_workers,
    "hierarchical": _g_hierarchical,
    "handoff_network": _g_handoff_network,
}
