"""Single agent with tools: one tool-use loop owns the whole task.

Generated by VG Select: 3A (Automated Agentic Architecture) v0.3.0. Search for TODO."""

from langgraph.graph import END, START, StateGraph

from .agents import last_text, role_agent
from .state import State
from .tools import TOOLS

SYSTEM = (
    "TODO: role, goal and boundaries. Say which tools to prefer and when to stop. "
    "Ask for clarification only when the request is ambiguous."
)


def agent(state: State) -> dict:
    runner = role_agent("agent", SYSTEM, TOOLS)
    result = runner.invoke({"messages": [("user", state["request"])]})
    return {"answer": last_text(result), "messages": result["messages"]}


def build_graph():
    g = StateGraph(State)
    g.add_node("agent", agent)
    g.add_edge(START, "agent")
    g.add_edge("agent", END)
    return g.compile()
