"""Router: a small-model classifier dispatches to one specialist.

Generated by VG Select: 3A (Automated Agentic Architecture) v0.3.0. Search for TODO."""

from typing import Literal

from pydantic import BaseModel
from langgraph.graph import END, START, StateGraph

from .agents import chat_model, last_text, role_agent
from .state import State
from .tools import TOOLS

ROUTES = {"handler_1": "financial planning specialist", "handler_2": "tax specialist", "handler_3": "risk specialist", "handler_4": "products specialist"}


class Route(BaseModel):
    route: Literal['handler_1', 'handler_2', 'handler_3', 'handler_4']


def router(state: State) -> dict:
    llm = chat_model("router", max_tokens=64).with_structured_output(Route)
    choices = "\n".join(f"- {k}: {v}" for k, v in ROUTES.items())
    decision = llm.invoke([("system", "Classify the request into exactly one route:\n" + choices), ("user", state["request"])])
    return {"route": decision.route}


def handler_1(state: State) -> dict:
    """Handles 'financial planning' requests with only that domain's instructions and tools."""
    runner = role_agent("handler_1", "TODO: system prompt for financial planning specialist: only this domain's instructions and tools.", TOOLS)
    result = runner.invoke({"messages": [("user", state["request"])]})
    return {"answer": last_text(result), "messages": result["messages"]}


def handler_2(state: State) -> dict:
    """Handles 'tax' requests with only that domain's instructions and tools."""
    runner = role_agent("handler_2", "TODO: system prompt for tax specialist: only this domain's instructions and tools.", TOOLS)
    result = runner.invoke({"messages": [("user", state["request"])]})
    return {"answer": last_text(result), "messages": result["messages"]}


def handler_3(state: State) -> dict:
    """Handles 'risk' requests with only that domain's instructions and tools."""
    runner = role_agent("handler_3", "TODO: system prompt for risk specialist: only this domain's instructions and tools.", TOOLS)
    result = runner.invoke({"messages": [("user", state["request"])]})
    return {"answer": last_text(result), "messages": result["messages"]}


def handler_4(state: State) -> dict:
    """Handles 'products' requests with only that domain's instructions and tools."""
    runner = role_agent("handler_4", "TODO: system prompt for products specialist: only this domain's instructions and tools.", TOOLS)
    result = runner.invoke({"messages": [("user", state["request"])]})
    return {"answer": last_text(result), "messages": result["messages"]}


def build_graph():
    g = StateGraph(State)
    g.add_node("router", router)
    g.add_node("handler_1", handler_1)
    g.add_node("handler_2", handler_2)
    g.add_node("handler_3", handler_3)
    g.add_node("handler_4", handler_4)
    g.add_edge(START, "router")
    g.add_conditional_edges("router", lambda s: s["route"], {h: h for h in ROUTES})
    g.add_edge("handler_1", END)
    g.add_edge("handler_2", END)
    g.add_edge("handler_3", END)
    g.add_edge("handler_4", END)
    return g.compile()
